// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Infrastructure.Data;

#nullable disable

namespace RecipeShare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250626064430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeShare.Domain.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<string>("DietaryTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = 45,
                            DietaryTags = "Gluten-Free",
                            Ingredients = "Chicken, Curry",
                            Steps = "Cook",
                            Title = "Chicken Curry"
                        },
                        new
                        {
                            Id = 2,
                            CookingTime = 5,
                            DietaryTags = "Vegan",
                            Ingredients = "Lettuce, Tomato",
                            Steps = "Toss",
                            Title = "Salad"
                        },
                        new
                        {
                            Id = 3,
                            CookingTime = 60,
                            DietaryTags = "High-Protein",
                            Ingredients = "Beef, Potatoes",
                            Steps = "Boil",
                            Title = "Beef Stew"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
